// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
. . . . . 2 2 e e . . . . . 
. . . . . 2 f e e . . . . . 
. . f f e e e e e f f f . . 
. f f e e e 2 e f f f f f . 
. f f e d d d d d e f f f . 
. f d d d d d d d d d d f . 
. f d f d d d d d d f d f . 
e f d d d d f f d d d d f e 
. e d d d d d d d d d d e . 
. . e e e e e e e e e e . . 
. . . . f d d d d f . . . . 
. e e f f f e e f f f e e . 
e d d e f 5 e e f f e d d e 
e d d e f f e e f f e d d e 
. e e . c c c c c c . e e . 
. . . . c . . . . c . . . . 
. . . . c . . . . c . . . . 
`;
            case "-ke!GZ#c6z":
            case "bullet_initial":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . 4 4 . . . . . . . 
. . . . . . 4 5 5 4 . . . . . . 
. . . . . . 2 5 5 2 . . . . . . 
. . . . . . . 2 2 . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "dodge_roll_front":
            case "anim9":return [img`
. . . . . . . e e . . . . . . 
. . . . . e e e 2 2 . . . . . 
. . . . . e e 2 f f . . . . . 
. . f f f e e 2 e e f f f . . 
. f f f f e e 2 e e f f f f . 
. f f f e f e 2 2 e f f f f . 
. f f f d d d d d d d f f f . 
. f f d d d d d d d d d f f . 
. e f d f d d d d d f d f e . 
. e f d d d f f f d d d f e . 
. e e d d d f f f d d d e e . 
. . e e d d d d d d d e e . . 
. e d d e e e e e e e d d e . 
. e d d e e e e e e e d d e . 
. . e e f e e d d e f e e . . 
. . . f f e e e d e 5 f . . . 
. . . . f e e e e e f . . . . 
. . . . . c . . . c . . . . . 
. . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . e e 2 . . . . . . 
. . f f f e e 2 f f f f f . . 
. f f f f e e 2 e e f f f f . 
. f f f f e e 2 e e f f f f . 
. f f f e f e 2 2 e f f f f . 
. f f d f e e e 2 e f d f f . 
. e f d d d d d d d d d f e . 
. e f d f d d d d d f d f e . 
. e e e d d f f f d d e e e . 
. e d d e d f f f d e d d e . 
. e d d e e e e e e e d d e . 
. . e e f e e d d e f e e . . 
. . . f f e e e e e f f . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . f f f f f f f f f . . . 
. . f f f f e 2 f f f f f . . 
. f f f f e e 2 f f f f f f . 
. f f f e e e 2 e e f f f f . 
. f f f f e e 2 e e f f f f . 
. e f d f f e 2 2 e f d f e . 
. e f d d d d 2 2 e d d f e . 
. e f d f d d d d d f d f e . 
. e e d d d f f f d d d e . . 
. . e e e e e e e e e e e . . 
. . e e e e e d d e e e e . . 
. e d d e . . . . . e d d e . 
. e d d e . . . . . e d d e . 
. . e e . . . . . . . e e . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . c . . . . . c . . . . 
. . . . c . . . . . c . . . . 
. . . . c . . . . . c . . . . 
. . . c c c c c c c c c c . . 
. f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f . 
. f f f f f f 2 e f f f f f . 
. f f f f f 2 2 e f f f f f . 
. f f f f f 2 e e f f f f f . 
. f f f f f 2 e f f f f f f . 
. . f f d d e e d d d f f . . 
. . e e e e e e e e e e e . . 
. e d d e . . . . . e d d e . 
. e d d e . . . . . e d d e . 
. . e e . . . . . . . e e . . 
. . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . c . . . . . c . . . . 
. . . . c . . . . . c . . . . 
. . f f f f f f f f f f f . . 
. . c c c c c c c c c c c . . 
. . f f f f f f f f f f f . . 
. . f f f f f f f f f f f . . 
. . f f f f f 2 e f f f f . . 
. . f f f f f 2 e f f f f f . 
. f f f f f 2 2 e f f f f f . 
. f f f f f 2 e e f f f f f . 
. e f f f f 2 e f f f f f e . 
. e d d e d 2 e d d e d d e . 
. . e e e e e e e e e e e . . 
`, img`
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . c . . . . . c . . . . 
. . . . c . . . . . c . . . . 
. . . . c . . . . . c . . . . 
. . f c c c c c c c c c f . . 
. . f f f f f f f f f f f . . 
. . f f f f f f f f f f f . . 
. . e f f f f f f f f f e . . 
. e e f f e e e e e f f e e . 
. f f f f f f f f f f f f f . 
. . f f f e f f f f f f f . . 
. . f f f e e e e e f f f . . 
. . . f f f f f f f f f . . . 
`, img`
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . e e 2 e e . . . . . 
. . . e e e e 2 e e e e . . . 
. . e e f e e 2 e e f e e . . 
e e f f c f d d d f c f f e e 
d d f f f f d d d f f f f d d 
d d f f c f f f f f c f f d d 
e e f c c c c c c c c c f e e 
. . f c c c c c c c c c f . . 
. . e f f f f f f f f f e . . 
. . . e e e e e e e e e . . . 
`, img`
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . f f e 2 2 e f . . . . 
. . e e f e e e e f f e e . . 
. e d d e d d d d d e d d e . 
. e d d e d d d d d e d d e . 
. f e e f d d d d d f e e f . 
. f f e d d f f f d d e f f . 
. . f f f e e e e e f f f . . 
. . f f c f e e e f c f f . . 
. . f f c f f f f f c f f . . 
. . f f f f c c c f f f f . . 
. . . f c f f f f f c f . . . 
`, img`
. . . . . . . . . . . . . . . 
. . . . . e e e 2 2 . . . . . 
. . . . . e e 2 f f . . . . . 
. . f f e f e 2 2 e f f f . . 
. f f f d d d d d d d f f f . 
. f f d d d d d d d d d f f . 
. f f d f d d d d d f d f f . 
. e f d d d f f f d d d f e . 
. e f d d d d d d d d d f e . 
. e e d d d d d d d d d e e . 
. . e d d d d d d d d d e . . 
. . . e e e e e e e e e . . . 
. . e e f e e e e e f e e . . 
. e d d e e e d d e e d d e . 
. e d d e f e e d f e d d e . 
. . e e f c f e f c f e e . . 
. . . . . c f e f c . . . . . 
. . . . . c . . . c . . . . . 
. . . . . . . . . . . . . . . 
`];
            case "dodge_roll_back":
            case "anim11":return [img`
. . . . . . . e e . . . . . . 
. . . . . e e e 2 2 . . . . . 
. . . . . e e 2 f f . . . . . 
. . f f f f f 2 e e f f f . . 
. f f f f f f f e e f f f f . 
. f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f . 
. e f f f f f f f f f f f e . 
. e f f f f f f f f f f f e . 
. e e f f f f f f f f f e e . 
. . e e d d d d d d d e e . . 
. e d e f f f f f f f e d e . 
. e d f f f f f f f f f d e . 
. . e f f f f f f f f f e . . 
. . . f f f f f f f f f . . . 
. . . . c c c c c c c . . . . 
. . . . c . . . . . c . . . . 
. . . . c . . . . . c . . . . 
`, img`
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . e e 2 . . . . . . 
. . . . . e e 2 f f . . . . . 
. . f f f e e 2 e e f f f . . 
. f f f f f f f e f f f f f . 
. f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f . 
. e f f f f f f f f f f f e . 
. e d f f f f f f f f f d e . 
. e d d f f f f f f f f d e . 
. . e f f f f f f f f f e . . 
. . . f f f f f f f f f . . . 
. . . . c c c c c c c . . . . 
. . . . c . . . . . c . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . e e 2 f f . . . . . 
. . f f f e e f f f f f f . . 
. f f f f f f e f f f f f f . 
. f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f . 
. e f d f f f f f f f f f e . 
. e d f f f f f f f f f d e . 
. e d f f f f f f f f f d e . 
. . e f c c c c c c c f e . . 
. . . . c . . . . . c . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . c . . . . . c . . . . 
. . . . c . . . . . c . . . . 
. . f f c f f f f f c f f . . 
. f f f f f c c c f f f f f . 
. e f f f f f f f f f f f e . 
. e f f e e e e e e e f f e . 
. e f f e e e e e e e f f f . 
. f f d d e e e e e d d f f . 
. f f d d d d d d d d d f f . 
. f f d f d d d d d f d f f . 
. f f f e e 2 2 e e f f f f . 
. . e e e e e e e e f e e . . 
. e d d e . . . . . e d d e . 
. e d d e . . . . . e d d e . 
. . e e . . . . . . . e e . . 
. . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . c . . . . . c . . . . 
. . . . c . . . . . c . . . . 
. . . f c f c c c f c f . . . 
. . f e f f f f f f f e f . . 
. f e f e e e e e e e f e f . 
. e e e e e e e e e e e e e . 
. e f d d d d d d d d d f e . 
. e f d d d d d d d d d f f . 
. f e e f d d d d d f e e f . 
. e d d e e 2 2 2 e e d d e . 
. e d d e e 2 2 e e e d d e . 
. . e e e f e e e f e e e . . 
`, img`
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . c . . . . . c . . . . 
. . . f c f f f f f c f . . . 
. . f f c f f f f f c f f . . 
. f e d f d d d d d f d e f . 
. e e d d d d d d d d d d e . 
. e f d f d d d d d f d f e . 
. e f f f e 2 2 2 e f f f f . 
. f f f f e 2 2 2 e f f f f . 
. f e e f e 2 2 e e f e e f . 
. e d d e e e e e e e d d e . 
`, img`
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . e e e e e e e e e . . . 
. . e d d d d d d d d d e . . 
. f f d f f e e 2 f f d f f . 
. f f f f e e 2 e f f f f f . 
. f f f f e e 2 e e f f f f . 
. e f f f f e e 2 f f f f e . 
. e d f f f e e e f f f d e . 
. e f f f f f f f f f f f e . 
. . e f f f f f f f f f e . . 
. . . f f f f f f f f f . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . e e f e e 2 f e e . . . 
. . e d d e e 2 f f d d e . . 
. f f d f e e 2 e e f d f f . 
. f f f f f e e 2 f f f f f . 
. f f f f f e e e f f f f f . 
. e f f f f f f f f f f f e . 
. e d f f f f f f f f f d e . 
. e f f f f f f f f f f f e . 
. . e f f f f f f f f f e . . 
. . f f f f f f f f f f f . . 
. . . f f f f f f f f f . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . e e 2 . . . . . . 
. . . . . e e 2 f f . . . . . 
. . f f f e e 2 e e f f f . . 
. f f f f f e e e f f f f f . 
. f f f f f e e f f f f f f . 
. f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f . 
. e f f f f f f f f f f f e . 
. e d f f f f f f f f f d e . 
. e d d f f f f f f f f d e . 
. . e f f f f f f f f f e . . 
. . . f f f f f f f f f . . . 
. . . f f f f f f f f f . . . 
. . . f f e e e e e f f . . . 
. . . . c . . . . . c . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
`];
            case "run_front_pilot":
            case "anim5":return [img`
. . . . . 2 2 e e . . . . . . 
. . . . . 2 f e e . . . . . . 
. . f f e 2 e e e f f f . . . 
. f f f e e e e e f e f f . . 
. f f f d d d d d d f f f . . 
. f d d d d d d d d d d f . . 
. f d d d d d d d d d d f . . 
e f d f d d d d d d f d f e . 
e e d d d d f f d d d d e e . 
. . e e e e e e e e e e . . . 
. . e f f f d d f f f e . . . 
. e e f f 5 e e f f f e e . . 
. e e f f f e e f f f e e . . 
e d d e f 5 e e f f e d d e . 
. e e f f f b b f f f e e . . 
. . . . c c c c c c . . . . . 
. . . . c . . . . c . . . . . 
. . . . c . . . . . . . . . . 
`, img`
. . . . 2 2 . . . . . . . . . 
. . . . 2 f e e e . . . . . . 
. f f f e e 2 e e f f f . . . 
f f f f e 2 2 e e f f f . . . 
f f f f d d 2 e f e f f f . . 
f f d d d d d d d d f d f . . 
f f d f d d f f f d d d f e . 
e f d d d d d d d d d d e e . 
. e d d d d d d d d e e . . . 
. . e e e e e e e e f f . . . 
. e d d e f f d d d f f f e . 
. . e e f f f e e e e f f d . 
. . . . f f 5 e e e e f f e . 
. . . . f f f e e e f f c . . 
. . . . f f f f c c f c f . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
`, img`
. . . . 2 2 . . . . . . . . . 
. . . . 2 f e e . . . . . . . 
. . . f 2 e 2 e f f . . . . . 
f f f f e 2 2 e e f f . . . . 
f f f e d d 2 f d f f f . . . 
f f f d d d d d d d d f . . . 
f f d d d d d d d f d f . . . 
f f d f d d f f d d d f e . . 
e e d d d d d d d d d e . . . 
. e d d d d d d d e e . . . . 
. . e e e e e e e f f f e . . 
. . e e f f 5 d e f f f e e . 
. e d d e f f e e f f e d d . 
. . e e f f f e e f f f e e . 
. . . . f f f b b f f f . . . 
. . . . . c c c c c c c . . . 
. . . . . . . . . . . c . . . 
. . . . . . . . . . . . . . . 
`, img`
. . . . . 2 2 e e . . . . . . 
. . . . . 2 f e e . . . . . . 
. . f f e 2 e e e f f f . . . 
. f f f e e e e e f e f f . . 
. f f f d d d d d d f f f . . 
. f d d d d d d d d d d f . . 
. f d d d d d d d d d d f . . 
e f d f d d d d d d f d f e . 
e e d d d d f f d d d d e e . 
. . e e e e e e e e e e . . . 
. . e f f f d d f f f e . . . 
. e e f f 5 e e f f f e e . . 
. e e f f f e e f f f e e . . 
e d d e f 5 e e f f e d d e . 
. e e f f f b b f f f e e . . 
. . . . c c c c c c . . . . . 
. . . . c . . . . c . . . . . 
. . . . . . . . . c . . . . . 
`, img`
. . . . . . . 2 e e e . . . . 
. . . . . f f 2 2 e e . . . . 
. . . . f f f 2 2 e e e f f . 
. . . . f f f e 2 e f e e f f 
. . . f d d d d d d d d f f f 
. . . f d f d d d d d d d f f 
. . . f d d d f f d d f d f f 
. . . e d d d d d d d d d f e 
. . . . f f e e e e e e e . . 
. . . e f f f d d f e e e . . 
. . e e f 5 e e e e d d e e . 
. e e f f f e e e e d d e . . 
e d d e f 5 e e e f e e . . . 
. e e . f c f b b f f f . . . 
. . . . f c f c f f f . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
`, img`
. . . . . . . 2 e e e . . . . 
. . . . . f f 2 2 e e . . . . 
. . . . f f f 2 2 e e e f f . 
. . . . f f f e 2 e f e e f f 
. . . f d d d d d d d d f f f 
. . . f d f d d d d d d d f f 
. . . f d d d f f d d f d f f 
. . . e d d d d d d d d d f e 
. . . . f f e e e e e e e . . 
. . . e f f f d d f e e e . . 
. . e e f 5 e e e e d d e e . 
. e e f f f e e e e d d e . . 
e d d e f 5 e e e f e e . . . 
. e e . f c f b b f f f . . . 
. . . . f c f c f f f . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
`];
            case "run_back_player":
            case "anim8":return [img`
. . . . . 2 2 e e e . . . . . 
. . . . . 2 f 2 e e . . . . . 
. . f f e 2 e f f f f f f . . 
. f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f . 
e f f f f f f f f f f f f f e 
e e d f f f f f f f f f d e e 
. e d d f f f f f f f d d e . 
. . e e e e e e e e e e e . . 
. . e f f f e e e f f f e . . 
. e e f f f f f f f f f e e . 
e d d f f f f f f f f f d d e 
. e e f f f f f f f f f e e . 
. . . f f f f f f f f f . . . 
. . . f c f c c c c c . . . . 
. . . . . . . . . . c . . . . 
. . . . . . . . . . c . . . . 
`, img`
. . . . . . . . . . . 2 2 . . 
. . . . . . . . e e e f 2 . . 
. . . . . f f f e e 2 e 2 . . 
. . . . f f f f e f f f f f f 
. . . . f f f f f f f f f f f 
. . . f f f f f f f f f f f f 
. . . f f f f f f f f f f f f 
. . e f f f f f f f f f f f f 
. . e e d f f f f f f f f f f 
. . . e d d f f f f f f f f e 
. . . . e e e f f f f f d d e 
. . . f f f e e e e e e e e . 
. e e f f f e e e e f f e . . 
e d f f f f f f f f f f d e . 
. e f f f f f f f f f f e . . 
. . f f f f f f f f f f . . . 
. . . f f f f f f f f . . . . 
. . . c . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . 2 2 . . . 
. . . . . . . e e e f 2 . . . 
. . . . . f f e e 2 e 2 f . . 
. . . . f f f e e 2 e e e f f 
. . . . f f f e e f e f f f f 
. . . f f f f e f f f f f f f 
. . . f f f f f f f f f f f f 
. . e f f f f f f f f f f f f 
. . e e d f f f f f f f f f f 
. . . e d f f f f f f f f f f 
. . . f e e f f f f f f f f e 
. . e f f f d f f f f f f e . 
. e e f f f f f e e e f f e . 
e d f f f f f f f f f f . . . 
. e f f f f f f f f f f . . . 
. . . f f f f f f f f f . . . 
. . . c c c c c c f c f . . . 
. . . c . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
`, img`
. . . . . e e e 2 2 . . . . . 
. . . . . e e 2 f 2 . . . . . 
. . f f f f f f e 2 e f f . . 
. f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f . 
. f f f f f f f f f f f f f . 
e f f f f f f f f f f f f f e 
e e d f f f f f f f f f d e e 
. e d d f f f f f f f d d e . 
. . e e e e e e e e e e e . . 
. . e f f f e e e f f f e . . 
. e e f f f f f f f f f e e . 
. . e f f f f f f f f f e . . 
. . . f f f f f f f f f . . . 
. . . f f f f f f f f f . . . 
. . . . c c c c c f c f . . . 
. . . . c . . . . . . . . . . 
. . . . c . . . . . . . . . . 
`, img`
. . . . 2 2 . . . . . . . . . 
. . . . 2 f e e . . . . . . . 
. . . f 2 e 2 e f f . . . . . 
. f f f f f f e f f f . . . . 
f f f f f f f f f f f . . . . 
f f f f f f f f f f f f . . . 
f f f f f f f f f f f f . . . 
f f f f f f f f f f f f e . . 
e f f f f f f f f f d e e . . 
e e f f f f f f f d d e . . . 
. e d d f f f f e e e . . . . 
. e e e e e e e e f f f . . . 
. e d e f f e e e f f f e e . 
. . . f f f f f f f f f d d . 
. . . f f f f f f f f f d d . 
. . . f f f f f f f f f e e . 
. . . . f f f f f f f f . . . 
. . . . . . . . . . . c . . . 
. . . . . . . . . . . . . . . 
`, img`
. . . . . . 2 2 . . . . . . . 
. . . e e e f 2 . . . . . . . 
. . f e e 2 e 2 f f . . . . . 
f f f e e 2 e e e f f . . . . 
f f f e f f f f f f f f . . . 
f f f f f f f f f f f f . . . 
f f f f f f f f f f f f . . . 
f f f f f f f f f f f f e . . 
f f f f f f f f f f d e e . . 
e f f f f f f f f e e f . . . 
. e f f f f f f d f f f e . . 
. e f f e e e f f f f f e e e 
e d f f f f f f f f f f e d d 
e d f f f f f f f f f f e d d 
. . f f f f f f f f f f . . . 
. . . f c f c c c c c c . . . 
. . . . . . . . . . . c . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
`];
            case "run_right_pilot0":
            case "anim7":return [img`
. . . . . . . . . . . . . . . 
. . . . . . . . e e e e . . . 
. . f f f f f f e e 2 f f . . 
. f f f f f f f e e 2 e e f . 
. f f f f f f e e e 2 e e f . 
. f f f f f f d f e 2 2 e e . 
. f e e f d d d d d d d d e . 
. f e d f d f d d d d d f e . 
. f e e f d d d f f f d d e . 
. . e d d d d d d d d d d e . 
. . . e e e e e e e e e e . . 
. . . . f f e e e e e f . . . 
. . . e e f e e d d e f e . . 
. . e d d e f e e e e 5 d e . 
. . . e e f f e e e e f e . . 
. . . . . f . . . . f . . . . 
. . . . . c . . . . . . . . . 
. . . . . c . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . 
. . . . . . f f f f f . . . . 
. . . . f f f e 2 2 f e . . . 
. . . f f f f e e e 2 e e . . 
. f f f f f f f e e 2 2 e . . 
. f f f f f d d d d d d d e . 
. f f f f d d d d d d d f e . 
. f f f f d d d d d d d d e . 
. f e e f d f d f f f d d e . 
. f e d f d d d d d d d e . . 
. . . . e e e e e d d e f e . 
. . . . f e e e e e e e 5 . . 
. . . . e e d d e e e e e f . 
. . . . e e d d e e e e f f c 
. . . . . f e e f . . . . . c 
. . . . . . c . . . . . . . . 
. . . . . c . . . . . . . . . 
. . . . . . . . . . . . . . . 
`, img`
. . . . . . 2 e . . . . . . . 
. . . . . e e 2 f e . . . . . 
. . . . . e e e 2 e e f . . . 
. . . f f e e e 2 2 e f f . . 
. f f f f f d d d d d d e . . 
. f f f f f d d d d d d d e . 
. f f f f d d d d d d d f e . 
. f f f f d d d d d d d d e . 
. f e e f d f d f f f d d e . 
. . f e d d d d d e e e f . . 
. . . . e e e e e d d e f e . 
. . . . f e f e e e e e 5 . . 
. . . . e e e e e e e e e f . 
. . . . e e d d e e e e e f . 
. . . . . . e e f . . . . c c 
. . . . . . c c . . . . . . c 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
`, img`
. . . . . . . e e 2 f . . . . 
. . f f f f f f e e 2 e e . . 
. f f f f f f f e e 2 e e f . 
. f f f f f f e f e 2 2 e f . 
. f f f f f f d d d d d d e . 
. f f f f d d d d d d d d e . 
. f e e f d d d d d d d d e . 
. f e d f d f d d d d d f e . 
. f e e f d d d f f f d d e . 
. . e d d d d d d d d d d e . 
. . . . f f e e e e e f . . . 
. . . e e f e e d d e f e . . 
. . e d d e f e e e e f d e . 
. . e d d e f e e e e 5 d e . 
. . . e e f f e e e e f e . . 
. . . . . f . . . . f . . . . 
. . . . . . . . . . c . . . . 
. . . . . . . . . . c . . . . 
`, img`
. . . f f f f f f f f f . . . 
. . f f f f f f f e e e f . . 
. . f f f f f f f e 2 e e f . 
. . f f f f f f e f e 2 e e . 
. f e d f d d d d d d 2 d e . 
. f e e f d f d d d d d d e . 
. . f e d d d d d d d d f e . 
. . f e d d d d f f f d d e . 
. . . e e e e d d d d d d e . 
. e d d e f e e e e e . e e . 
. e d d e f f e d d e e d d e 
. . e e f f e e e e e e d d e 
. . . f f f e e e e 5 f e e . 
. . . . f c . . f f . . . . . 
. . . . . . . . c . . . . . . 
. . . . . . . c . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
`, img`
. . . f f f f f f f f . . . . 
. . f f f f f f e 2 e f . . . 
. . f f f f f f f 2 2 f . . . 
. f f f f f f f f 2 2 e f . . 
. f e f f d d d d d d d e . . 
. e d f d d d d d d d d e . . 
. f e d d f d d d d d d e . . 
. f e d d d d d d d d f e . . 
. . e e d d d f f f d d e . . 
. . e f e d d d d d d d e . . 
. e e e f e e e e e e e e e . 
e d d e f e e e e e f e d d e 
. e e f f e e e e 5 f . e e . 
. . . f f e e e e f . . . . . 
. . . c . . . . . . . . . . . 
. . . . c . . . . . . . . . . 
. . . . c . . . . . . . . . . 
. . . . . . . . . . . . . . . 
`];
            case "run_right_pilot":
            case "anim6":return [img`
. . . . . . . . . . . . . . . 
. . . e e e e . . . . . . . . 
. . f f 2 e e f f f f f f . . 
. f e e 2 e e f f f f f f f . 
. f e e 2 e e e f f f f f f . 
. e e 2 2 e f d f f f f f f . 
. e d d d d d d d d f e e f . 
. e f d d d d d f d f d e f . 
. e d d f f f d d d f e e f . 
. e d d d d d d d d d d e . . 
. . e e e e e e e e e e . . . 
. . . f e e e e e f f . . . . 
. . e f e d d e e f e e . . . 
. e d 5 e e e e f e d d e . . 
. . e f e e e e f f e e . . . 
. . . . f . . . . f . . . . . 
. . . . . . . . . c . . . . . 
. . . . . . . . . c . . . . . 
`, img`
. . . . . . . . . . . . . . . 
. . . . f f f f f . . . . . . 
. . . e f 2 2 e f f f . . . . 
. . e e 2 e e e f f f f . . . 
. . e 2 2 e e f f f f f f f . 
. e d d d d d d d f f f f f . 
. e f d d d d d d d f f f f . 
. e d d d d d d d d f f f f . 
. e d d f f f d f d f e e f . 
. . e d d d d d d d f d e f . 
. e f e d d e e e e e . . . . 
. . 5 e e e e e e e f . . . . 
. f e e e e e d d e e . . . . 
c f f e e e e d d e e . . . . 
c . . . . . f e e f . . . . . 
. . . . . . . . c . . . . . . 
. . . . . . . . . c . . . . . 
. . . . . . . . . . . . . . . 
`, img`
. . . . . . . e 2 . . . . . . 
. . . . . e f 2 e e . . . . . 
. . . f e e 2 e e e . . . . . 
. . f f e 2 2 e e e f f . . . 
. . e d d d d d d f f f f f . 
. e d d d d d d d f f f f f . 
. e f d d d d d d d f f f f . 
. e d d d d d d d d f f f f . 
. e d d f f f d f d f e e f . 
. . f e e e d d d d d e f . . 
. e f e d d e e e e e . . . . 
. . 5 e e e e e f e f . . . . 
. f e e e e e e e e e . . . . 
. f e e e e e d d e e . . . . 
c c . . . . f e e . . . . . . 
c . . . . . . c c . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
`, img`
. . . . f 2 e e . . . . . . . 
. . e e 2 e e f f f f f f . . 
. f e e 2 e e f f f f f f f . 
. f e 2 2 e f e f f f f f f . 
. e d d d d d d f f f f f f . 
. e d d d d d d d d f f f f . 
. e d d d d d d d d f e e f . 
. e f d d d d d f d f d e f . 
. e d d f f f d d d f e e f . 
. e d d d d d d d d d d e . . 
. . . f e e e e e f f . . . . 
. . e f e d d e e f e e . . . 
. e d f e e e e f e d d e . . 
. e d 5 e e e e f e d d e . . 
. . e f e e e e f f e e . . . 
. . . . f . . . . f . . . . . 
. . . . c . . . . . . . . . . 
. . . . c . . . . . . . . . . 
`, img`
. . . f f f f f f f f f . . . 
. . f e e e f f f f f f f . . 
. f e e 2 e f f f f f f f . . 
. e e 2 e f e f f f f f f . . 
. e d 2 d d d d d d f d e f . 
. e d d d d d d f d f e e f . 
. e f d d d d d d d d e f . . 
. e d d f f f d d d d e f . . 
. e d d d d d d e e e e . . . 
. e e . e e e e e f e d d e . 
e d d e e d d e f f e d d e . 
e d d e e e e e e f f e e . . 
. e e f 5 e e e e f f f . . . 
. . . . . f f . . c f . . . . 
. . . . . . c . . . . . . . . 
. . . . . . . c . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
`, img`
. . . . f f f f f f f f . . . 
. . . f e 2 e f f f f f f . . 
. . . f 2 2 f f f f f f f . . 
. . f e 2 2 f f f f f f f f . 
. . e d d d d d d d f f e f . 
. . e d d d d d d d d f d e . 
. . e d d d d d d f d d e f . 
. . e f d d d d d d d d e f . 
. . e d d f f f d d d e e . . 
. . e d d d d d d d e f e . . 
. e e e e e e e e e f e e e . 
e d d e f e e e e e f e d d e 
. e e . f 5 e e e e f f e e . 
. . . . . f e e e e f f . . . 
. . . . . . . . . . . c . . . 
. . . . . . . . . . c . . . . 
. . . . . . . . . . c . . . . 
. . . . . . . . . . . . . . . 
`];
            case "still_down":
            case "anim1":return [img`
. . . . . 2 2 e e . . . . . 
. . . . . 2 f e e . . . . . 
. . f f e e e e e f f f . . 
. f f e e e 2 e f f f f f . 
. f f e d d d d d e f f f . 
. f d d d d d d d d d d f . 
. f d f d d d d d d f d f . 
e f d d d d f f d d d d f e 
. e d d d d d d d d d d e . 
. . e e e e e e e e e e . . 
. . . . f d d d d f . . . . 
. e e f f f e e f f f e e . 
e d d e f 5 e e f f e d d e 
e d d e f f e e f f e d d e 
. e e . c c c c c c . e e . 
. . . . c . . . . c . . . . 
. . . . c . . . . c . . . . 
`, img`
. . . . . . . . . . . . . . 
. . . . . 2 2 e e . . . . . 
. . f f e 2 e e e f f f . . 
. f f e e e e e e f f f f . 
. f f e d e 2 e f e f f f . 
. f f d d d d d d d d f f . 
. f d d d d d d d d d d f . 
e f d f d d d d d d f d f e 
e e d d d d f f d d d d e e 
. e d d d d d d d d d d e . 
. . . . f f e e f f . . . . 
. . e f f f e e f f f e . . 
. e e f f f e e f f f e e . 
e d d e f 5 e e f f e d d e 
. e e . c c c c c c . e e . 
. . . . c . . . . c . . . . 
. . . . c . . . . c . . . . 
`, img`
. . . . . . . . . . . . . . 
. . . . . . e e . . . . . . 
. . f f e 2 f e e f f f . . 
. f f e e 2 e e e f f f f . 
. f f e d e e e e e f f f . 
. f f d d e 2 e f d d f f . 
. f d d d d d d d d d d f . 
e f d f d d d d d d f d f e 
e e d d d d f f d d d d e e 
. e d d d d d d d d d d e . 
. . . . f f e e f f . . . . 
. . e f f f e e f f f e . . 
. e e f f f e e f f f e e . 
e d d e f 5 e e f f e d d e 
. e e . c c c c c c . e e . 
. . . . c . . . . c . . . . 
. . . . c . . . . c . . . . 
`];
            case "back_player":
            case "anim4":return [img`
. . . . . e e 2 2 . . . . . 
. . . . . e e f 2 . . . . . 
. . f f f f f e 2 e f f . . 
. f f f f f f f f f f f f . 
. f f f f f f f f f f f f . 
. f f f f f f f f f f f f . 
. f f f f f f f f f f f f . 
e f f f f f f f f f f f f e 
. e d d f f f f f f d d e . 
. . e e e e e e e e e e . . 
. . e f f f e e f f f e . . 
. e e f f f f f f f f e e . 
e d d f f f f f f f f d d e 
. e e f f f f f f f f e e . 
. . . . c c c c c c . . . . 
. . . . c . . . . c . . . . 
. . . . c . . . . c . . . . 
`, img`
. . . . . . . . . . . . . . 
. . . . . e e 2 2 . . . . . 
. . f f f f f e 2 e f f . . 
. f f f f f f f f f f f f . 
. f f f f f f f f f f f f . 
. f f f f f f f f f f f f . 
. f f f f f f f f f f f f . 
e f f f f f f f f f f f f e 
. e d d f f f f f f d d e . 
. . e e e e e e e e e e . . 
. . e f f f e e f f f e . . 
. e e f f f f f f f f e e . 
. e e f f f f f f f f e e . 
e d d f f f f f f f f d d e 
. e e . c c c c c c . e e . 
. . . . c . . . . c . . . . 
. . . . c . . . . c . . . . 
`, img`
. . . . . e e 2 2 . . . . . 
. . f f f f f e 2 e f f . . 
. f f f f f f f f f f f f . 
. f f f f f f f f f f f f . 
. f f f f f f f f f f f f . 
. f f f f f f f f f f f f . 
e f f f f f f f f f f f f e 
e e d f f f f f f f f d e e 
. . e e e e e e e e e e . . 
. . e f f f e e f f f e . . 
. e e f f f f f f f f e e . 
. e e f f f f f f f f e e . 
e d d f f f f f f f f d d e 
. e e f f f f f f f f e e . 
. . . . c c c c c c . . . . 
. . . . c . . . . c . . . . 
. . . . c . . . . c . . . . 
`, img`
. . . . . . e e e . . . . . 
. . . . . e e 2 2 . . . . . 
. . f f f f e f 2 e f f . . 
. f f f f f f f f f f f f . 
. f f f f f f f f f f f f . 
. f f f f f f f f f f f f . 
. f f f f f f f f f f f f . 
e f f f f f f f f f f f f e 
e e d f f f f f f f f d e e 
. . e e e e e e e e e e . . 
. . e f f f e e f f f e . . 
. e e f f f f f f f f e e . 
. e e f f f f f f f f e e . 
e d d f f f f f f f f d d e 
. e e f f f f f f f f e e . 
. . . . c c c c c c . . . . 
. . . . c . . . . c . . . . 
`];
            case "side_rigth":
            case "anim2":return [img`
. . . . . . . e e e 2 2 . . . 
. . . . . . . e e 2 f f . . . 
. f f f f f f e e 2 e e . . . 
f f f f f f f e e 2 e e f . . 
f f f f d d d d d d d d e . . 
f f f f d d d d d d d d e . . 
f e e f d d d d d d d d e . . 
f e d f d f d d d d d f e . . 
f e e f d d d f f f d d e . . 
. . e e d d d d d d d d . . . 
. . . f f e e e e e f . . . . 
. . e e f e e d d e f e . . . 
. e e e f f e e e e f e e e . 
. e d d e f e e e e 5 e d d e 
. . e e f f e e e e f . e e . 
. . . . c c c c c c . . . . . 
. . . . c . . . . c . . . . . 
`, img`
. . . . . . . . . . . . . . . 
. . . . . . e e e 2 2 . . . . 
. . . . . . e e 2 f f . . . . 
f f f f f f f e e 2 e e f . . 
f f f f f f e f e 2 2 e f . . 
f f f f d d d d d d d d e . . 
f f f f d d d d d d d d e . . 
f e d f d f d d d d d f e . . 
f e e f d d d f f f d d e . . 
. e e e d d d d d d d d e . . 
. . . f f e e e e e f . . . . 
. . e e f e e d d e f e e . . 
. e d d e f e e e e e d d e . 
. e d d e f e e e e 5 d d e . 
. . e e f f e e e e f e e . . 
. . . . c c c c c c . . . . . 
. . . . c . . . . c . . . . . 
`, img`
. . . . . . . . . e e e 2 2 . 
. . f f f f f f f e e 2 f f . 
. f f f f f f f f e e 2 e e . 
. f f f f f f e f e e 2 e e . 
. f f f f d d d d d d d d e . 
. f e e f d d d d d d d d e . 
. f e d f d f d d d d d f e . 
. f e e f d d d f f f d d e . 
. . e e e d d d d d d d d e . 
. . . e e e e e e e e e e . . 
. . . . f f e e d d e f . . . 
. . e e e f f e e e e f e e . 
. . e d d e f e e e e e d d e 
. . e d d e f e e e e 5 d d e 
. . . e e f f e e e e f e e . 
. . . . . c c c c c c . . . . 
. . . . . c . . . . c . . . . 
`, img`
. . . . . . . . . e e e 2 2 . 
. . f f f f f f f e e 2 f f . 
. f f f f f f f f e e 2 e e . 
. f f f f d d d d e 2 2 e f . 
. f f f f d d d d d d d d e . 
. f e e f d d d d d d d d e . 
. f e d f d f d d d d d f e . 
. f e e f d d d f f f d d e . 
. . . e e d d d d d d d d . . 
. . . . f f e e e e e f . . . 
. . . e e f e e d d e f e . . 
. . e e e f f e e e e f e . . 
. . . e e f f e e e e 5 e e . 
. . e d d e f e e e e e d d e 
. . . e e c c c c c c . e e . 
. . . . . c . . . . c . . . . 
. . . . . c . . . . c . . . . 
`];
            case "side_left":
            case "anim3":return [img`
. . . 2 2 e e e . . . . . . . 
. . . f f 2 e e . . . . . . . 
. . . e e 2 e e f f f f f f . 
. . f e e 2 e e f f f f f f f 
. . e d d d d d d d d f f f f 
. . e d d d d d d d d f f f f 
. . e d d d d d d d d f e e f 
. . e f d d d d d f d f d e f 
. . e d d f f f d d d f e e f 
. . . d d d d d d d d e e . . 
. . . . f e e e e e f f . . . 
. . . e f e d d e e f e e . . 
. e e e f e e e e f f e e e . 
e d d e 5 e e e e f e d d e . 
. e e . f e e e e f f e e . . 
. . . . . c c c c c c . . . . 
. . . . . c . . . . c . . . . 
`, img`
. . . . . . . . . . . . . . . 
. . . . 2 2 e e e . . . . . . 
. . . . f f 2 e e . . . . . . 
. . f e e 2 e e f f f f f f f 
. . f e 2 2 e f e f f f f f f 
. . e d d d d d d d d f f f f 
. . e d d d d d d d d f f f f 
. . e f d d d d d f d f d e f 
. . e d d f f f d d d f e e f 
. . e d d d d d d d d e e e . 
. . . . f e e e e e f f . . . 
. . e e f e d d e e f e e . . 
. e d d e e e e e f e d d e . 
. e d d 5 e e e e f e d d e . 
. . e e f e e e e f f e e . . 
. . . . . c c c c c c . . . . 
. . . . . c . . . . c . . . . 
`, img`
. 2 2 e e e . . . . . . . . . 
. f f 2 e e f f f f f f f . . 
. e e 2 e e f f f f f f f f . 
. e e 2 e e f e f f f f f f . 
. e d d d d d d d d f f f f . 
. e d d d d d d d d f e e f . 
. e f d d d d d f d f d e f . 
. e d d f f f d d d f e e f . 
. e d d d d d d d d e e e . . 
. . e e e e e e e e e e . . . 
. . . f e d d e e f f . . . . 
. e e f e e e e f f e e e . . 
e d d e e e e e f e d d e . . 
e d d 5 e e e e f e d d e . . 
. e e f e e e e f f e e . . . 
. . . . c c c c c c . . . . . 
. . . . c . . . . c . . . . . 
`, img`
. 2 2 e e e . . . . . . . . . 
. f f 2 e e f f f f f f f . . 
. e e 2 e e f f f f f f f f . 
. f e 2 2 e d d d d f f f f . 
. e d d d d d d d d f f f f . 
. e d d d d d d d d f e e f . 
. e f d d d d d f d f d e f . 
. e d d f f f d d d f e e f . 
. . d d d d d d d d e e . . . 
. . . f e e e e e f f . . . . 
. . e f e d d e e f e e . . . 
. . e f e e e e f f e e e . . 
. e e 5 e e e e f f e e . . . 
e d d e e e e e f e d d e . . 
. e e . c c c c c c e e . . . 
. . . . c . . . . c . . . . . 
. . . . c . . . . c . . . . . 
`];
            case "dodge_roll_rigth":
            case "anim10":return [img`
........ee2f.........
.......eeee22f.......
.....ffffffee2e......
....fffffffee2ef.....
...fffffffefe22e.....
...fffffdddddddef....
...ffffddddddddde....
....fefddfdddddfe....
....edffdddfffdde....
...ffeefdddfffdde....
..feeffeeddddddde....
.feeeeeeeeeeeeeeee...
.feeeeddeeef...edde..
.ffffeddef.....edde..
.cccffeec.......ee...
ccc....c.............
cc...................
.....................
.....................
`, img`
.....................
...........eee22.....
............ee2ff....
.......ffffffee2ee...
......fffffffee2eef..
......ffffffefe22ef..
......ffffffdddddde..
......ffffdddddddde..
......feefdfdddddfe..
...ccffedfdddfffdde..
...ffffeefdddfffdde..
..ffffefeeedddddddee.
cccffeeeeddeeeeeeeede
...eeeeeeddeef...edde
....eeeffeef......ee.
.....................
.....................
.....................
.....................
`, img`
.....................
.....................
...........ee2.......
..........eee2ff.....
......ffffffee2ee....
.....fffffffee2eef...
.....ffffffefe2eef...
.....ffffffddd22ef...
.....ffffdddddddde...
..c..feefdfdddddfe...
..cc.fedfdddfffdde...
..ffffeefdddfffdde...
cffffeeddddddddddeee.
ccffeeeeeeeeeeeeeedde
...eeeeeeddef....edde
...eeeeeedde......ee.
.........ee..........
.....................
.....................
`, img`
.....................
.....................
.....................
.....................
.........e2..........
.....ffffee22f.......
....fffffee2fff......
...fffffffee2eef.....
...fffffffee2eef.....
.c.feefdfefe22ee.....
.ccfedfdddddddde.....
...feefdddddddde.....
...ffefdfdddddfe.....
....feeeeeeeeeeee....
....eddeeeee..edde...
....edde......edde...
.....ee........ee....
.....................
.....................
`, img`
.....................
.....................
.....................
.....................
.....................
.....................
.....................
.....c...............
.c.ffffffffee........
.cfffffffee2ee.......
.ffffffffee2eef......
..ffefffefe22ee......
..fedeffefe22ee......
..feffffefe22ee......
..fffddfefe22ee......
...feeddefe22dee.....
...eddeddfe2dedde....
...eddeeeeeeeedde....
....ee........ee.....
`, img`
.....................
.....................
.....................
.....................
.....................
..........c..........
.....c....c..........
.....c..fffffff......
....cfffffffffff.....
....cfeeffffffff.....
.....feeffffffff.....
.....feeefffffff.....
.....ffefffffffff....
.....eeffffffffff....
.....eddeffffffff....
....eedeeffffffff....
...eddedeeefffff.....
...eddedeefefff......
....eeeeeeeeffe......
`, img`
.....................
.....................
.....................
.....................
.....................
.....................
.....................
........cc...cc......
.......fcffffff......
......effffffff......
...eeeeefffffff......
..eddeeffffffff......
..eddefffffffff......
...eedeffffffff......
...edeeffffffff......
...eddeffffffff......
...eeeeeffffff.......
....eeeffffff........
.....eee.............
`, img`
.....................
.....................
.....................
.....................
.....................
.....................
.....................
.....................
.......22............
......ee22f..........
...eeeeee22fee.......
..eddeddddddfde......
..eddefdfdfffdf......
...eeefddfccffcc.....
...fedfddefccffcc....
...ffeddeefccffcc....
...ffffdefffff.......
....ffeeeffff........
.....fffeeff.........
`, img`
.....................
.....................
.......ee2f..........
......ee2feff........
...fffeee2eef........
.fffffeee22ee........
.ffffffee22de........
.fffffddddddde.......
.ffffdddddddfe.......
.ffffdddddddde.......
.feefdfdfffdde.......
.fedfdddddddee.......
..fedddddeee5........
....eeeeeddec........
....effffeeecc.......
.....fffcfee.c.......
.....fffcc...........
.........c...........
.....................
`];
            case "dodge_roll_left":
            case "anim12":return [img`
.........f2ee........
.......f22eeee.......
......e2eeffffff.....
.....fe2eefffffff....
.....e22efefffffff...
....fedddddddfffff...
....edddddddddffff...
....efdddddfddfef....
....eddfffdddffde....
....eddfffdddfeeff...
....edddddddeeffeef..
...eeeeeeeeeeeeeeeef.
..edde...feeeddeeeef.
..edde.....feddeffff.
...ee.......ceeffccc.
.............c....ccc
...................cc
.....................
.....................
`, img`
.....................
.....22eee...........
....ff2ee............
...ee2eeffffff.......
..fee2eefffffff......
..fe22efeffffff......
..eddddddffffff......
..eddddddddffff......
..efdddddfdfeef......
..eddfffdddfdeffcc...
..eddfffdddfeeffff...
.eedddddddeeefeffff..
edeeeeeeeeddeeeeffccc
edde...feeddeeeeee...
.ee......feeffeee....
.....................
.....................
.....................
.....................
`, img`
.....................
.....................
.......2ee...........
.....ff2eee..........
....ee2eeffffff......
...fee2eefffffff.....
...fee2efeffffff.....
...fe22dddffffff.....
...eddddddddffff.....
...efdddddfdfeef..c..
...eddfffdddfdef.cc..
...eddfffdddfeeffff..
.eeeddddddddddeeffffc
eddeeeeeeeeeeeeeeffcc
edde....feddeeeeee...
.ee......eddeeeeee...
..........ee.........
.....................
.....................
`, img`
.....................
.....................
.....................
.....................
..........2e.........
.......f22eeffff.....
......fff2eefffff....
.....fee2eefffffff...
.....fee2eefffffff...
.....ee22efefdfeef.c.
.....eddddddddfdefcc.
.....eddddddddfeef...
.....efdddddfdfeff...
....eeeeeeeeeeeef....
...edde..eeeeedde....
...edde......edde....
....ee........ee.....
.....................
.....................
`, img`
.....................
.....................
.....................
.....................
.....................
.....................
.....................
...............c.....
........eeffffffff.c.
.......ee2eefffffffc.
......fee2eeffffffff.
......ee22efefffeff..
......ee22efeffedef..
......ee22efeffffef..
......ee22efefddfff..
.....eed22efeddeef...
....edded2efddedde...
....eddeeeeeeeedde...
.....ee........ee....
`, img`
.....................
.....................
.....................
.....................
.....................
..........c..........
..........c....c.....
......fffffff..c.....
.....fffffffffffc....
.....ffffffffeefc....
.....ffffffffeef.....
.....fffffffeeef.....
....fffffffffeff.....
....ffffffffffee.....
....ffffffffedde.....
....ffffffffeedee....
.....fffffeeededde...
......fffefeededde...
......effeeeeeeee....
`, img`
.....................
.....................
.....................
.....................
.....................
.....................
.....................
......cc...cc........
......ffffffcf.......
......ffffffffe......
......fffffffeeeee...
......ffffffffeedde..
......fffffffffedde..
......ffffffffedee...
......ffffffffeede...
......ffffffffedde...
.......ffffffeeeee...
........ffffffeee....
.............eee.....
`, img`
.....................
.....................
.....................
.....................
.....................
.....................
.....................
.....................
............22.......
..........f22ee......
.......eef22eeeeee...
......edfddddddedde..
......fdfffdfdfedde..
.....ccffccfddfeee...
....ccffccfeddfdef...
....ccffccfeeddeff...
.......fffffedffff...
........ffffeeeff....
.........ffeefff.....
`, img`
.....................
.....................
..........f2ee.......
........ffef2ee......
........fee2eeefff...
........ee22eeefffff.
........ed22eeffffff.
.......edddddddfffff.
.......efdddddddffff.
.......eddddddddffff.
.......eddfffdfdfeef.
.......eedddddddfdef.
........5eeedddddef..
........ceddeeeee....
.......cceeeffffe....
.......c.eefcfff.....
...........ccfff.....
...........c.........
.....................
`];
            case "cultistAnimation":
            case "anim13":return [img`
. . . . . . . . . . . . . . 
. . c c a a a a a a c . . . 
. c c c a a a a a a a c . . 
c c c c c a c c c c a a . . 
c f f f f f f f f f c c . . 
c f f f f f f f f f f c c . 
c f 4 f f f f f 4 f f c c . 
c f f f f f f f f f f c c . 
c c f f f f f f f c c c . . 
. c c f f f f f c c c f . . 
. f f f f f f f f f f c . . 
. c a a a f a a a c c c . . 
. e 4 4 4 4 4 4 4 e e . . . 
. a a a 4 f 4 a c c c c . . 
. a a a 4 f a a c c c c c . 
. a a a a f a a c c c c c . 
`, img`
. . c c a a a a a a a c c . 
. c c c a a a a a a a a c c 
c c c c c a c c c c c a a a 
c c f f c c f f f f c a c c 
c f f f f f f f f f f c c c 
c f f f f f f f f f f f c c 
c f 4 f f f f f f 4 f f c c 
c f f f f f f f f f f f c c 
c f f f f f f f f f f c c c 
c c f f f f f f f f c c c c 
f c c f f f f f f c c c f f 
. c a a a f a a a a c c c . 
. c a a a f a a a a c c c . 
c e 4 4 4 4 4 4 4 4 e e e . 
c a a a 4 f 4 a a c c c c c 
c a a a a f a a a c c c c . 
`, img`
. . . c c a a a a a a a c . 
. . c c c a a a a a a a a c 
. c c c c c a c c c c c a a 
. c c f f c c f f f f c a c 
. c f f f f f f f f f f c c 
. c f f f f f f f f f f f c 
. c f f f f f f f f f f f c 
. c f 4 f f f f f f 4 f f c 
. c f f f f f f f f f f c c 
. f c f f f f f f f f c c f 
. . f c f f f f f f c c f c 
. . c f f f f f f f f f c c 
. . c a a a f a a a a c c . 
. . e 4 4 4 4 4 4 4 4 e e . 
. c a a a 4 f 4 a a c c c c 
. c a a a 4 f a a a c c c c 
`, img`
. . c c a a a a a a a c . . 
. c c c a a a a a a a a c . 
c c c c c a c c c c c a a c 
c c f f c c f f f f c a c c 
c f f f f f f f f f f c c c 
c f f f f f f f f f f f c c 
c f 4 f f f f f f 4 f f c c 
c f f f f f f f f f f f c c 
f c f f f f f f f f c c f c 
. f c f f f f f f c c f c c 
. c f f f f f f f f f c c c 
. c a a a f a a a a c c c c 
. e 4 4 4 4 4 4 4 4 e e . . 
c a a a 4 f 4 a a c c c . . 
c a a a 4 f a a a c c c c . 
c a a a 4 f a a a c c c c . 
`];
            case "bullet":
            case "anim14":return [img`
....bbbbbb....
...bb1dccbb...
..bbd1dcccbb..
..bbbdbbccbb..
.bbd1dbbbccbb.
.bbd1dbbbccbb.
.bbbddbbccbbb.
..eeeeeeeeee..
.445dd5555444.
.445dd5555444.
.445dd5555444.
.445dd5555444.
.445dd5555444.
.445dd5555444.
.4f5dfff5f444.
.445dd5555444.
.445dd5555444.
..eeeeeeeeee..
.445dd5555444.
.444444444444.
..e5e....e5e..
...e......e...
`, img`
....bbbbbb....
...bb1dccbb...
..bbd1dcccbb..
..bbbdbbccbb..
.bbd1dbbbccbb.
.bbd1dbbbccbb.
.bbbddbbccbbb.
..eeeeeeeeee..
.445dd5555444.
.445dd5555444.
.445dd5555444.
.445dd5555444.
.445dd5555444.
.445dd5555444.
.4f5dfff5f444.
.445dd5555444.
.445dd5555444.
..eeeeeeeeee..
.445dd5555444.
.444444444444.
..e5e....e5e..
...e......e...
`, img`
.....bbbb.....
....bbbbbb....
...bb1dccbb...
..bbd1dcccbb..
..bbbdbbccbb..
.bbd1dbbbccbb.
.bbd1dbbbccbb.
.bbbddbbccbbb.
..eeeeeeeeee..
.445dd5555444.
.445dd5555444.
.445dd5555444.
.445dd5555444.
.445dd5555444.
.445dd5555444.
.4f5dfff5f444.
.445dd5555444.
.445dd5555444.
..eeeeeeeeee..
.445dd5555444.
.444444444444.
..e55e..e55e..
`];
            case "Bullet_NPC_Animation":
            case "anim15":return [img`
......bbbb......
.....bbbbbb.....
....bbcdccbb....
...bbdcdcccbb...
...bbbdbbccbb...
..bbdcdbbbccbb..
..bbdcdbbbccbb..
..bbbddbbccbbb..
...eeeeeeeeee...
..445dd5555444..
..445dd5555444..
..445dd5555444..
..445dd5555444..
..445dd5555444..
..445dd5555444..
..445dd5555444..
..4f5dffff54f4..
..445dd5555444..
..2eeeeeeeeee2..
..445dd5555444..
.24444444444442.
.22e5effffe5e22.
.22feffffffef22.
`, img`
................
......bbbb......
.....bbbbbb.....
....bbcdccbb....
...bbdcdcccbb...
...bbbdbbccbb...
..bbdcdbbbccbb..
..bbdcdbbbccbb..
..bbbddbbccbbb..
...eeeeeeeeee...
..445dd5555444..
..445dd5555444..
..445dd5555444..
..445dd5555444..
..445dd5555444..
..445dd5555444..
..445dd5555444..
..4f5dffff54f4..
..445dd5555444..
..2eeeeeeeeee2..
.2445dd55554442.
2244444444444422
22fe5effffe5ef22
`, img`
................
................
......bbbb......
.....bbbbbb.....
....bbcdccbb....
...bbdcdcccbb...
...bbbdbbccbb...
..bbdcdbbbccbb..
..bbdcdbbbccbb..
..bbbddbbccbbb..
...eeeeeeeeee...
..445dd5555444..
..445dd5555444..
..445dd5555444..
..445dd5555444..
..445dd5555444..
..445dd5555444..
..445dd5555444..
..4f5dffff54f4..
..445dd5555444..
..2eeeeeeeeee2..
.2445dd55554442.
2f444444444444f2
`];
            case "myAnim":
            case "anim16":return [img`
...bbbbb.......
..bbbbbbb......
.bb1bcccbb.....
.bd1dccccbb....
bbbddbbcccbb...
bd1dbbbbccbb...
bd1dbbbccbbb...
bbddbbbeeeee...
bbbeeee2224ee..
.be244422224eee
.e22244eeeeeeee
.e2eeee5555444e
.eee5dd5555444.
..445dd5555444.
..445dd55555444
..445dd55f55444
..4f5fff5555444
...445dd5555ee.
...445ddeeee5e4
...44eee5555e5e
....e45dd444.e.
.....4444......
.....e55e......
`, img`
...............
...bbbbb.......
..bbbbbbb......
.bbbcbcbbb.....
.bd11cccbbb....
bbb1dcccbbbb...
bdbdbbbcccbb...
bd11bbbccccb...
bb1dbbbbbcbe...
bbbdbbbbbbeeee.
.bbbdbbbee42eee
.eeeeeee22242ee
.e22442222ee44e
.e222442ee5544.
..eeeeee555544.
..445dd55555544
..445dd55555544
..4455dd55f5544
...445fff555544
...4f5dd5555e44
...445ddd55e5e.
....445dd544e..
.....44444.....
`, img`
.....bbbb......
....bbbbbb.....
...bb1dccbb....
..bbd1dcccbb...
..bbbdbbccbb...
.bbd1dbbbccbb..
.bbd1dbbbccbb..
.bbbddbbccbbb..
.eeeeeeeeeeee..
.e2244224242e..
.e2244222424ee.
.eeeeeeeeeeeeee
.445dd5555444ee
.445dd5555444e.
.445dd5555444..
.4f5dfff5f444..
.445dd5555444..
.445dd5555444..
..eeeeeeeeee...
.445dd555e444..
.4444444e5e44..
..e5e....e.....
...e...........
`, img`
......bbbbbbb..
.....bbd1ddbbb.
.....bb1dddcbb.
....bb1ddbbccbb
...bbd1dbbccbbb
...bbbdbbbcccbb
...eeeedbbcccbb
...e224eeeecbbb
..e22244222eee.
..eeeee422222e.
..4455deeee22e.
..445dd5555eeee
.4455dd555554ee
.445dd5555544e.
.4f5dd5555544..
445dfff555544..
ee5dd555f554...
44eee5555544...
455ddeeee544...
.44445554ee....
.....4444......
......e5e......
.......e.......
`, img`
...............
........bbbb...
......bbbbbbb..
.....bb11dcbbb.
....bb1ddcccbb.
....bdddbbccbbb
....eeeebbcccbb
....2244eeeccbb
...e2244222eebb
...eeeee22242e.
..4455ddeee24e.
..4455dd555eee.
..445dd555554ee
.4455dd555554ee
.4f5fff555544e.
.445dd55f5544..
.eeedd5555544..
4444eeee5544...
44444444e544...
5e4444444e44...
e444444444e....
....444444.....
......e55e.....
`, img`
.....bbbb......
....bbbbbb.....
...bb1dccbb....
..bbd1dcccbb...
..bbbdbbccbb...
.bbd1dbbbccbb..
.bbd1dbbbccbb..
.bbbddbbccbbb..
.eeeeeeeeeeee..
.e2244224242e..
.e2244222424ee.
.eeeeeeeeeeeeee
.445dd5555444ee
.445dd5555444e.
.445dd5555444..
.4f5fff55f444..
.445dd5555444..
.445dd5555444..
..4eeeeeeeee...
.4e4dd5555444..
.e5e444444444..
..e.......e5e..
...........e...
`];
            case "myAnim0":
            case "anim17":return [img`
.......bbbbb...
......bbbbbbb..
.....bbcccb1bb.
....bbccccd1db.
...bbcccbbddbbb
...bbccbbbbd1db
...bbbccbbbd1db
...eeeeebbbddbb
..ee4222eeeebbb
eee422224442eb.
eeeeeeee44222e.
e4445555eeee2e.
.4445555dd5eee.
.4445555dd544..
44455555dd544..
44455f55dd544..
4445555fff5f4..
.ee5555dd544...
4e5eeeedd544...
e5e5555eee44...
.e.444dd54e....
......4444.....
......e55e.....
`, img`
...............
.......bbbbb...
......bbbbbbb..
.....bbbcbcbbb.
....bbbccc11db.
...bbbbcccd1bbb
...bbcccbbbdbdb
...bccccbbb11db
...ebcbbbbbd1bb
.eeeebbbbbbdbbb
eee24eebbbdbbb.
ee24222eeeeeee.
e44ee22224422e.
.4455ee244222e.
.445555eeeeee..
44555555dd544..
44555555dd544..
4455f55dd5544..
445555fff544...
44e5555dd5f4...
.e5e55ddd544...
..e445dd544....
.....44444.....
`, img`
......bbbb.....
.....bbbbbb....
....bbccd1bb...
...bbcccd1dbb..
...bbccbbdbbb..
..bbccbbbd1dbb.
..bbccbbbd1dbb.
..bbbccbbddbbb.
..eeeeeeeeeeee.
..e2424224422e.
.ee4242224422e.
eeeeeeeeeeeeee.
ee4445555dd544.
.e4445555dd544.
..4445555dd544.
..444f5fffd5f4.
..4445555dd544.
..4445555dd544.
...eeeeeeeeee..
..444e555dd544.
..44e5e4444444.
.....e....e5e..
...........e...
`, img`
..bbbbbbb......
.bbbdd1dbb.....
.bbcddd1bb.....
bbccbbdd1bb....
bbbccbbd1dbb...
bbcccbbbdbbb...
bbcccbbdeeee...
bbbceeee422e...
.eee22244222e..
.e222224eeeee..
.e22eeeed5544..
eeee5555dd544..
ee455555dd5544.
.e4455555dd544.
..4455555dd5f4.
..445555fffd544
...455f555dd5ee
...4455555eee44
...445eeeedd554
....ee45554444.
......4444.....
......e5e......
.......e.......
`, img`
...............
...bbbb........
..bbbbbbb......
.bbbcd11bb.....
.bbcccdd1bb....
bbbccbbdddb....
bbcccbbeeee....
bbcceee4422....
bbee2224422e...
.e24222eeeee...
.e42eeedd5544..
.eee555dd5544..
ee455555dd544..
ee455555dd5544.
.e445555fff5f4.
..4455f55dd544.
..4455555ddeee.
...4455eeee4444
...445e44444444
...44e4444444e5
....e444444444e
.....444444....
.....e55e......
`, img`
......bbbb.....
.....bbbbbb....
....bbccd1bb...
...bbcccd1dbb..
...bbccbbdbbb..
..bbccbbbd1dbb.
..bbccbbbd1dbb.
..bbbccbbddbbb.
..eeeeeeeeeeee.
..e2424224422e.
.ee4242224422e.
eeeeeeeeeeeeee.
ee4445555dd544.
.e4445555dd544.
..4445555dd544.
..444f55fff5f4.
..4445555dd544.
..4445555dd544.
...eeeeeeeee4..
..4445555dd4e4.
..444444444e5e.
..e5e.......e..
...e...........
`];
            case "bullet_key_kill":
            case "anim19":return [img`
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
..................................bc..................................
.................................bbbbcc...............................
.................................bbbbcc...............................
.................................bbbbcc...............................
.................................bbbbcc...............................
.................................bbc..................................
.................................bbbbc................................
.................................bbbbc................................
.................................bbc..................................
...............................bbbbbbb................................
..............................bbbbbccbb...............................
.............................bbbbbbcccbb..............................
............................bbbbbbbbccbbb.............................
............................bbcccccccccbb.............................
.............................cbbbbbbbbbc..............................
............................bbbbbbbbbbbbb.............................
...........................bbbbbbbbbbbbbbb............................
..........................c1ccbbbbbbbbbcc1............................
..........................bbbbbcbbbbbcbbbb............................
..........................bbbbbcccccccbbbb............................
..........................bbbbbcbbbbbcbbbb............................
...........................bbbbbbbbbbbbbbb............................
...........................bbbbbbbbbbbbbbb............................
...........................bbbbbbbbbbbbbbb............................
............................ccccccccccccc.............................
`, img`
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
...............................bbccccc................................
.............................bbccccccccb..............................
...........................bbbcccccccccccb............................
..........................bbbcccccccccccccb...........................
.........................bbbbcccccccccccccbb..........................
........................bbbbcccccccccccccccbb.........................
.......................bbbbcccfffffffffcccccbb........................
......................bbbbbccffffffffffffcccbbb.......................
......................bbbbbcffffffffffffffccbbb.......................
.....................bbbbbbcffffffffffffffccbbbb......................
.....................bbbbbbffffffffffffffffcbbbb......................
.....................bbbbbbffffffffffffffffcbbbb......................
....................bbbbbbbbfffffffffffffffbbbbb......................
....................bbbbbbbbbfffffffffffffbbfffb......................
....................bbbbbbbbbfffffffffffffbbff1f......................
....................bbfffbbbbbfffffffffffbbbffff......................
....................bb1ffbbbbbbffffffffbbbbbfffb......................
....................bbfffbbbbbbbbfffffbbbbbbbbbb......................
.....................bbbbbbbbbbbbbbbbbbbbbbbbbbb......................
.....................bbbbbbbbbbbbbbbbbbbbbbbbbbb......................
.....................bbbbbbbbbbbbbbbbbbbbbbbbbbb......................
......................bbbbbbbbbbbbbbbbbbbbbbbbb.......................
......................bbbbbbbbbbbbbbbbbbbbbbbbb.......................
.......................bbbbbbbbbbbbbbbbbbbbbbb........................
........................bbbbbbbbbbbbbbbbbbbbb.........................
.........................bbbbbbbbbbbbbbbbbbb..........................
..........................bbbbbbbbbbbbbbbbb...........................
...........................bbbbbbbbbbbbbbb............................
`, img`
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
....................................b.................................
......................................................................
.............................................b........................
.................................bbbb.................................
.............................bbbbbbbbbb.b......b......................
............................bbbbbbbbbbb.......bbbb....................
...........................bbbbbbbbbbbb....44bbbbbb...................
.......................b...bbbbbbbbbbbb...444bbbbbbb..................
...........................bbbbbbbbbbb.444444bbbbbbbbb................
...........................bbbbbbbbbb..4444444cccbbbbb................
...........................bbbbbbbbb..444444444cccbbbb................
.........................444bbbbbb...4444444444ccccbbbb...............
........................444444444....4444bb44444ccccbbb...............
.......................bb44444444....444bbb444444cccbbb...............
....................bbbbbb4444444...4444bbbb444444cccb................
...................bbbbbbb44444444.44444bbbb44444444cb................
..................bbbbbbbb444444444444444b4444444444bb................
..................bbbbbbcc4444444444444444444444dddd44................
.................bbbbbbccc444bb44444444444b4444ddddd44................
.................bbbbbcccc44bbb4444444444444444dddddd4................
.................bbbbcccc444bbb4444444444444444ddddddd4...............
.................bbbbccc44444444444ddd44d444444ddddddd4...............
.................bbdddcc4444444444dddd4dd44444dddddddd4...............
.................bbdddd4dd4444444dddddddd44444ddddddddd...............
..................dddddddd4444444dddddddd44444ddddddddd...............
..................dddddddd444444ddddddddd4444dddddddddd...............
...............dddddddddddd444ddddddddddddd4ddddddddddd4..............
...............dddddddddddddd4dddddddddddddddddddddddddd..............
...............ddddddddddddddddddddddddddddddddddddddddd..............
...............dddddddddddddddddddddddddddddddddddddddd...............
...............ddddddddddddddddddddddddddddd44dddddddd4...............
...............dddddddddddddddddddddddddddddd44ddddddd444.............
..............ddddddddddddd444ddddddddddddddd44dddd444444.............
.............dddddddddddddd4444dddddddddddddd44dddd444444.............
.............ddddddddddddd444dddddddddddddddd4444dddd44444............
.............ddddddddddddddd444dddddddddddddd4444ddddd44444...........
..............ddddddddddddddd4444dddddddddddd4444ddddd444444..........
.............ddddddddddddddddd44444ddddddddddd44dddddd4444444.........
...........ddddddd4dddddddddddd4444ddddddddddd4444dddd4444444.........
...........ddddddd4dd44ddddddd44444ddddddddddd4444dddd4444444.........
...........dd4ddd444444ddddddd4444dddddddddddd4444dddddd44444.........
............d4d44444444ddd4dddd4444dddddddddd44444ddddddd4444.........
............444444444444d444dddd4444dddddddd444444444dd444444.........
...........4444444444444444dddddd444dddddddddd44444444d444444.........
.............44444444444444dddddd4444ddddddd44444444444444444.........
......................44444ddddddd4444dddd4444444444444444444.........
.......................44444dddddddd444dd4444444444...4444444.........
........................44444dddddddd44444444444444...................
.........................44444dddddd444444444444444...................
..........................444444dddd44444444444.......................
..............................444dd4444.4444444.......................
...............................4444444...4444.........................
`, img`
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................4444e...........................
.....................................44444e...........................
....................................4444444e..........................
....................................4444444e..........................
....................................4444444e..........................
....................................444444ee..........................
..............................444..4444444ee..44.4....................
.............................4444444444444eee.4444....................
.............................4444444444444ee44444444..................
..........................44444444e4444444ee44444444..................
..........................4444444ee4444444e4444444444.................
..........................4444444e4444444ee4444444444.................
.........................4444444eeeeeeeeee4444444444ee................
.........................4444444eeeeeeeeee444444444eee................
........................e44eeeeeeeeeeeeeee44444444eeeee...............
.........................eeeeeeeeeeeeeeeeeee44444eeeeee...............
.........................eeedeeeeeeeeeeeeeeeeeeeeeeeeee...............
.........................eeeddeeeeeeeeeeeeeeeeeeeeeeeee...............
........................ddddddd4eeeeeeeeeeeeeeeedddddeee..............
........................dddddd44eeeeeeeeeeeeeeeedddddd................
........................ddddd444eeeeeeeeeeeeeeeedddddddd..............
........................ddddd444eeeeeeeeeeeeeeeedddddddd..............
.....................dddddddd444eeeeeeeeeeeeeeeddddddddd..............
.....................ddddddd44eeeeeeeeeeeeeeeedddddddddd..............
.....................ddddddd4e44eeeeeeeeeddeeedddddddddd..............
.....................dddddddeddddeeeeeddddddeeddddddd4444.............
....................ddddddddeddddeeeeedddddddeeddddddd444.............
....................ddddddddedddddeeeeddddddddddddddd444..............
...................ddddddd44ddddddeeedddddddddddd4dd4444..............
...................ddd444d4eddddd4eeeddddddddddd44444444..............
..................dddd44444eddddd44eedddddddddddd444444d44............
..................dddd44d44dddddd444eddddddddddddd444dddd4............
................ddddd444d44dddddd444eddddddddddddd44ddddd4............
................dd444dddd44444ddd444dddddddddddddd44ddddd.............
................dd444dddd444444d4444ddddddddddddd444ddddd4............
..............dddd4444dd444444444444ddddddddddddd44dddddd4............
.............dddd4444444444444444444ddddddddddddd44ddddddd............
.............d44444444444444444444444dddddddddddd44ddddddd44..........
............4444444444444444444444dd444dddddddddd44ddddddd444.........
..........444444444...........444dddd44dddddddd444444dddd4444.........
............44................444ddddd44dddd4444444444dd44444.........
...............................44dddddd44444444444444444444444........
................................44ddddd44444ddd444444444444444........
.................................44ddd44444ddddd444...444.............
.................................444444444dddddd4.....44..............
..................................4444444444dddd......................
.....................................44444444d44......................
.....................................444444.44444.....................
......................................44444..4444.....................
.........................................444..........................
`, img`
.....................................444..............................
.................................4444444..............................
................................44444444..............................
................................444444444.............................
..............................444eee44444.............................
............................4444ee.eeeeee4............................
............................4eeeee..eeeee44...........................
.........................4..eeeeee...ee.ee4...........................
.........................444eeeeee......ee4...........................
.........................4444e..ee.......ee...4...4...................
........................4444e............ee...44.444..................
........................4eeee................444.444..................
.......................41eee.................444.444..................
....................444eeeee....44...........4eee4444.................
...................4444eeeee...4444..........eeee444444...............
...................44eeeeeee..444444.........e.eeee4444...............
.................4444eeeeee...444444.........e.eeee4444...............
.................4e4eee..........eee.........e....ee444...............
.................4eeeee..........ee...............eee44...............
.................4ee.ee............................ee44...............
.................44e..................e............eeee...............
.................4eee.......5...444444ee....4.......eee...............
.................eeee......555.4444444ee...444.......ee...............
.................eee........5..4444444ee...44ee......e................
.................eee........5..4444444ee...44ee......e................
..................4edddd.......4444444ee....eee..dd..dd...............
.................4edddddd.......444eeeee.....e...dd..ddd..dd..........
.................4edddddd4......eeeeeeee.........dd..ddd..dd..........
...............d44ddddd444......eeeeeeee.........dd4.dddd.dd..........
..............dd44444444444..............5555.dddddddddddddd..........
............dddd44144444414...................ddddd4dddddddd..........
............dddd44444444.44...................ddd4444dd4d4dd..........
...........dddd4444.444..44..................dddd44444444ddd..........
..........ddddd4444.................ddd.ddd..dddd44444.44444..........
.........ddddd4444.................dddddddd..dddd44.44..4444..........
.........dddd444.......dd.44.......ddddddddd.444444.44....44..........
.........4dd4444......4dd4444......dddddddd44444444..4....44..........
.........4444444......ddd44444...dddddddddd44444.44.......44..........
.........4ddd444.....dddd4.4444.dddd4dd44444444..44........4..........
........4dddd44......ddd4...444.dddd444444.4444......5555.............
........ddddd44......ddd4...444.dddd44444...444.......................
.......ddddd444......4444...4444dddd44444...444.......................
......ddddd44.........4..5..44444444...4.............44.....4.........
......dddd444............5...4444444...4.............44.....44........
......ddd44.............5555..44.444.................44.....44........
......444444.............5....44..44.........................4........
.....41144.......4.................4.........................4........
....dd4114.......44...................................................
...ddd4444.......44...................................................
...ddd44.........44...................................................
..4444..................................5...444.......................
.414.........dd..dd....................5555.444.............dd........
..14.........ddddd44444.................5...44..............dd........
44444........dddd444444.................5...................dd........
4144......d4444444.44..4...............44..................ddd........
.444....444444444.........dd...........444.................ddddd......
......44..444..........4..dd.d........4444.................dddd44.....
.......................4.dddddd.......4444................dddd4444....
.......................44dddddd................d44ddddd.44444444444444
.........................44ddd4................dd44dddd4444444...44444
.........................444444................dd4444d44444444........
...........................444.................44..4.444..4444........
.............................4dd...............4......................
..............................dddddd...........4......................
..............................dddddddd.........4......................
..............................44444dddd...4...444.....................
..................................44444......ddd4.....................
...................................4444....44dd44.....................
....................................4444.....4444.....................
....................................444.444...........................
`, img`
....................................e.................................
......................................................................
..............................ee......................................
.......................................e..............................
.......................................ee.............................
..............................e........e.e............................
.........................ee...........................................
........................e.............................................
.............................................e.e......................
............................................e.........................
............................................e...e.....................
.................................................e....................
.....................ee.........................e.....................
.....................e................................................
....................e.................................................
.......................e......................e......e................
.....................................................e................
......................................................................
......................................................................
.................ee...............e...................................
..................e...............e...................................
..................e.........5.........................................
...................e........5.....e...................................
............................5.........................................
............................5..................4...4..................
.......................................e..............................
....................................e..e.........44...................
................................e.....................................
...............................ee........5..4........4................
.........................................5...........4..4.............
.....................................4..555...........................
.........................................54....4........4.............
...........4......................4.......4..............4............
...................4..................................................
......................................................................
............4............................................4............
......................................................................
........................................4..4..........................
......................................................................
........4..........................................555................
........4.............................................................
......................................................................
.....................................4................................
...........................................................4..........
........4................555..........................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
....4.............44...................5..............................
....................4.4...............555.............................
..44.........4.........................5..............................
...........44..........................5..............................
...........4..........................................................
.........4...................................................4........
..............................4...............4....4.........44.......
..............................4..............4....4.............4.....
..............................4.......................................
........................4.4...........................................
..............................................................4.......
..........................................................4...........
...........................4.............................4............
....................................................4.................
...............................4......................................
................................4.....................................
................................4.....................................
........................................44.....4......................
.................................4........4...4.......................
....................................4.....4...........................
`, img`
....................................ee................................
...................................e..................................
......................................................................
..............................e.......................................
......................................e...............................
......................................e...............................
......................................e.e.............................
........................ee............................................
......................ee..............................................
......................................................................
...........................................e..........................
...........................................e.e..e.....................
.................................................e....................
...................eee..........................e.....................
..................ee.e................................................
......................e..e...................e...e...e................
..............................................e......e................
.....................e..e................e...........e................
..........................................e...........................
.....................................................e................
...............ee................e....................................
................e................e....................................
................e.....................................................
..........................555.........................................
.........................................e..e.........................
..........................................e....4...4..................
.............................e.....e..e..........4....................
.............................e.......e................4.4.............
...............................e......................................
.............4................ee........5..4.........4................
....................................4..5554...........................
...................................44...5............4................
........................................5...............4.............
.........4.......................4.....4.................4............
...........................4..........................................
.....................4..4.......4.....................................
...........................4.............................4............
......................................................................
......................................................................
........4.............................................................
..................................................5555................
......................................................................
....................................4.................................
........................5.............................................
........................5..................................4..........
........................5.............................................
........................5.............................................
......................................................................
..4...................................................................
......................................................................
.4..............44....................5...............................
.............4....44..................5..................4............
4..........4..........................5...............................
.........4............................5...................4.4.........
.........4...................................................4........
...........................4..........................................
..............................................4....4..........4.......
.............................4..................................44....
......................................................................
......................4..4............................................
.............................................................4........
.......................................................4..............
.........................................................4............
..........................4.........................4.................
.............................44.......................................
...............................4......................................
...............................4......................................
........................................4.............................
................................4.........4..44.......................
...................................4......4...........................
`];
            case "key":
            case "anim20":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . f f . . . . . 
. . . . . . . . f c c f f . . . 
. . . . . . . f f c c c c f . . 
. . . . . . f f f c c f c f . . 
. . . . . f f f f f c c c c f . 
. . . . f f f c c f f c c c f . 
. . . f f f c c c c c f f f . . 
. . f f f f c c c c d c f . . . 
. f f c f f c d d d c f . . . . 
. f c c c c d f f f f . . . . . 
. . f c c d f . . . . . . . . . 
. . . f f f . . . . . . . . . . 
`, img`
. . . f f . . . . . . . . . . . 
. . f c c f . . . . . . . . . . 
. f c c c c f . . . . . . . . . 
. f d c c f f f . . . . . . . . 
. . f d c f c c f . . . . . . . 
. . . f d c f f f f f . . . . . 
. . . . f d c c c f f f . . . . 
. . . . . f d c c c f f f . . . 
. . . . . f d c c c c f f f . . 
. . . . . f d c c c c f f f f . 
. . . . . f c d c c f c f f . . 
. . . . . . f c d f c c f . . . 
. . . . . . . f f d c f . . . . 
. . . . . . . . f c f . . . . . 
. . . . . . . . . f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . f f . . 
. . . . . . . . . . . f d c f . 
. . . . . . . . . . f d c c c f 
. . . . . . . . . f d c f c c c 
. . . . f f f f f d c f f f c f 
. . . f c d d d d c f c f f f f 
. . f c d c c c c c f f c f f . 
. f f d c c c c c c f f f f . . 
f c d f c c c c c c f f f . . . 
. f c c f c c c c f f f . . . . 
. . f c c f f f f f f . . . . . 
. . . f f f f f f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . f f . . . 
. . . . . . . . . . f d c f . . 
. . . . . . . . . f d c c c f . 
. . . . . . . . f d c f c c c f 
. . . . f f f f d c f f f c f f 
. . . f c d d d c f c f f f f . 
. . f c d c c c c f f c f f . . 
. f f d c c c c c f f f f . . . 
f c d f c c c c f f . f . . . . 
. f c c f c c f f f . . . . . . 
. . f c c f f f f . . . . . . . 
. . . f f f f f . . . . . . . . 
. . . . f f f . . . . . . . . . 
. . . . . f . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . f f . . . 
. . . . . . . . . . f d c f . . 
. . . . . . . . . f d c c c f . 
. . . . . . . . f d c f c c c f 
. . . . f f f f d c f f f c f f 
. . . f c d d d c f c f f f f . 
. . f c d c c c c f f c f f . . 
. f f d c c c c c f f f f . . . 
f c d f c c c c f f . f . . . . 
. f c c f c c f f f . . . . . . 
. . f c c f f f f . . . . . . . 
. . . f f f f f . . . . . . . . 
. . . f f f f f . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . f f . . . 
. . . . . . . . . . f d c f . . 
. . . . . . . . . f d c c c f . 
. . . . . . . . f d c f c c c f 
. . . . f f f f d c f f f c f f 
. . . f c d d d c f c f f f f . 
. . f c d c c c c f f c f f . . 
. f f d c c c c c f f f f . . . 
f c d f c c c c f f . f . . . . 
. f c c f c c f f f . . . . . . 
. . f c c f f f f . . . . . . . 
. . . f f f f f . . . . . . . . 
. . . . f f f . . . . . . . . . 
. . . . . f . . . . . . . . . . 
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
